### PR TITLE
Fix/add missing fields for transaction retrieval via RPC

### LINKED ISSUE #170: RPC fields are different for pending/confirmed transactions
The field labels based on the `CMPPending` objects are different than the ones generated by the `populateRPC__()` functions.

An example for a DEx offer via `"omni_gettransaction"`:

```java
{
  "txid": "1c2a6e2b8a2f9ca8e46b5789c34d16a61a14a45379690b5a1e8cdba9cc6b384e",
  "sendingaddress": "mpm1kG5m94tJtySYY7dxvRCPcv8kyHx53r",
  "confirmations": 0,
  "type": "DEx Sell Offer",
  "amountoffered": "0.00000002", // <---
  "propertyidoffered": 1, // <---
  "btcamountdesired": "0.00000001", // <---
  "action": 1 // <---
}
```
```java
{
  "txid": "1c2a6e2b8a2f9ca8e46b5789c34d16a61a14a45379690b5a1e8cdba9cc6b384e",
  "sendingaddress": "mpm1kG5m94tJtySYY7dxvRCPcv8kyHx53r",
  "ismine": true,
  "confirmations": 1,
  "fee": "0.00010000",
  "blocktime": 1439303006,
  "valid": true,
  "version": 1,
  "type_int": 20,
  "type": "DEx Sell Offer",
  "propertyid": 1, // <---
  "divisible": true,
  "amount": "0.00000002", // <---
  "feerequired": "0.00000003",
  "timelimit": 10,
  "action": "new", // <---
  "bitcoindesired": "0.00000001" // <---
}
```

I started to map all values via OmniJ RPC tests, and I think it would be better to have the full picture, before taking action. I'll update, once ready or I need help.

### PR DESCRIPTION
**Pull request by dexX7**
- The field labels based on the CMPPending objects were  different than the ones generated by the populateRPC__() functions. The field names of the confirmed transaction objects was adopted.

- Not all stateless fields that can be returned were returned for confirmed transactions.

This PR resolves #170.

### CODE REVIEW

File: src/omnicore/rpctxobject.cpp [hunk 1]
```diff
@@ -256,6 +256,7 @@ void populateRPCTypeTradeOffer(CMPTransaction& omniObj, Object& txobj)
 
     // Check levelDB to see if the amount for sale has been amended due to a partial purchase
     // TODO: DEx phase 1 really needs an overhaul to work like MetaDEx with original amounts for sale and amounts remaining etc
+    // TODO: if the amount of the transaction is not used here, then the BTC amount should be recalculated (?)
```
Comment (zathras-crypto) [inline src/omnicore/rpctxobject.cpp]: Can you elaborate on this comment mate?

**Comment by zathras-crypto** [comment]
Reviewed, looks good to me, OK to merge.  Also like what you did with properties info :)

File: src/omnicore/rpctxobject.cpp (hunk 1 above)
Comment (dexX7) [inline src/omnicore/rpctxobject.cpp]: Sure:

Alice has only 50 MSC, but offers 1000 MSC for 1000 BTC. The (aweful) way how it's currently handled: the transaction is valid, and [the offer is adjusted](https://github.com/dexX7/bitcoin/blob/d761109327539abfd44af5e050f091ae32662db8/src/omnicore/dex.cpp#L131-L147) to 50 MSC for 50 BTC. The adjusted MSC amount is [fetched from the DB](https://github.com/dexX7/bitcoin/blob/0356f8f8399b6feac7d5e0d2fe7d62ee56016972/src/omnicore/rpctxobject.cpp#L264-L265), but the BTC amount isn't updated:

```java
omni_getbalance moR6aNzFHKSMUdqKb3vDCdetM7pLBHozKY 1
{
  "balance" : "50.00000000",  // <----
  "reserved" : "0.00000000"
}
```
```java
// DEx Offer of 1000 MSC for 1000 BTC
omni_sendrawtx "moR6aNzFHKSMUdqKb3vDCdetM7pLBHozKY" "0001001400000001000000174876e800000000174876e8000a000000000098968001"
f5c71761e1f6588784720bebf1eecbe3113b99a17d4857ec776352af566293ec
```
```java
setgenerate true 1
[
  "5a52c577e14918128425d182174cd6b36eaa17d1b92b68604145c5874476cedd"
]
```
```java
omni_gettransaction f5c71761e1f6588784720bebf1eecbe3113b99a17d4857ec776352af566293ec
{
  "txid": "f5c71761e1f6588784720bebf1eecbe3113b99a17d4857ec776352af566293ec",
  "fee": "0.00010000",
  "sendingaddress": "moR6aNzFHKSMUdqKb3vDCdetM7pLBHozKY",
  "ismine": true,
  "version": 1,
  "type_int": 20,
  "type": "DEx Sell Offer",
  "propertyid": 1,
  "divisible": true,
  "amount": "50.00000000",  // <----
  "bitcoindesired": "1000.00000000",  // <---- !!
  "timelimit": 10,
  "feerequired": "0.10000000",
  "action": "new",
  "valid": true,
  "blockhash": "5a52c577e14918128425d182174cd6b36eaa17d1b92b68604145c5874476cedd",
  "blocktime": 1439467162,
  "block": 103,
  "confirmations": 1
}
```

Comment (zathras-crypto) [inline src/omnicore/rpctxobject.cpp]: > The (aweful) way how it's currently handled

Ugh, agreed - the source of many a consensus mismatch in the early days when we had multiple implementations :(

>  but the BTC amount isn't updated

I see, thanks for the explanation - good catch.  Perhaps it would be better to handle it just like MetaDEx offers, where the "original amounts" can be provided along with the available (modified) values:

```
{
  ...
  "amountforsale" : 1000,
  "amountremaining" : 50,
  "amountdesired" : 1000.
  "amounttofill" : 50,
  "unitprice" : "1.00000000"
  ...
}
```

Comment (dexX7) [inline src/omnicore/rpctxobject.cpp]: I agree, this would probably be the way to go.

However, there is also a difference between "original amounts" and "the amounts of the transaction".

In the example above the "transaction amounts" are 1000.0/1000.0, while the "original amounts" are 50.0/50.0 (because only that much balance exists), whereby I mean with "original amount" the "amount initially up for sale".

Comment (zathras-crypto) [inline src/omnicore/rpctxobject.cpp]: Or, you know - we could just invalidate attempts to sell more than your balance hehe :)

Comment (dexX7) [inline src/omnicore/rpctxobject.cpp]: YES! :)

It's not backwards compatible though, and needs `legacy::` handling. There are historical transactions which would otherwise be invalid. (Same goes for two active DEx offers [MSC/TMSC] at the same time, which I checked, when I created #167))
